In [ ]:
from highway_extension.highway import ContinuousHighwayEnvironment, ContinuousHighwayEnvironmentConfig, HighwayReward
import torch
env = ContinuousHighwayEnvironment(
    config=ContinuousHighwayEnvironmentConfig(),
        reward=HighwayReward()
)




In [ ]:
torch.set_printoptions(precision=2, sci_mode=False)
env.reset()
from IPython.display import display, clear_output
for i in range(100):
    clear_output(wait=True)
    action = torch.tensor(env.action_space.sample())
    obs, reward, terminated, truncated, info = env.step(action)
    display(obs.reshape((1,16,14))[0,:,0:7])
    display(reward)
    if terminated.abs() >0:
        print("Terminated")
        break


In [3]:
import torch
torch.set_printoptions(precision=2, sci_mode=False)
x = torch.randn((1,3))
y = torch.randn((15,3))
print(x)
print(y)

_, indices = torch.sort((y-x).abs()[:,2])

n2 = y[indices[0:2]]

print(n2)

tensor([[ 0.31, -0.67, -0.63]])
tensor([[-0.53,  2.30,  0.97],
        [ 1.47,  0.28,  0.69],
        [-0.36, -1.82,  1.36],
        [-0.17, -1.23, -0.12],
        [-0.77, -1.47,  1.13],
        [-1.02,  0.93,  0.57],
        [ 1.18,  1.51, -0.15],
        [-1.66,  0.80, -0.21],
        [-0.79, -1.19, -0.15],
        [ 0.12,  0.20, -0.58],
        [-1.46,  1.05,  1.07],
        [ 1.75, -0.11,  1.53],
        [-1.85, -0.00,  0.25],
        [ 0.32, -0.56, -1.28],
        [ 1.71,  0.02, -0.50]])
tensor([[ 0.12,  0.20, -0.58],
        [ 1.71,  0.02, -0.50]])
