In [1]:
import torch

A = torch.arange(10)
B = torch.full((10,),False, dtype=torch.bool)
(A[B]).shape

torch.Size([0])

In [8]:
her_idx = torch.arange(10)[torch.rand(10) < 0.8]
print(her_idx)
mask_expert = torch.rand(her_idx.numel()) < 0.5 # shape = (her_batch,) dtype=bool
expert_local = torch.nonzero(mask_expert, as_tuple=False).flatten()
future_local = torch.nonzero(~mask_expert, as_tuple=False).flatten()
print(her_idx[expert_local], her_idx[future_local])

tensor([1, 2, 4, 5, 6, 8, 9])
tensor([2, 4, 8]) tensor([1, 5, 6, 9])


In [9]:
her_idx.numel()

7

In [10]:
a = torch.arange(10)
mask = (torch.rand(10) < 0.5).bool()

a[mask]

tensor([1, 3, 4, 5, 7, 8])